version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - s3

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5433:5433"

  s3:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
